[www]

; Définir l'utilisateur sous lequel PHP-FPM s'exécutera
user = www-data

; Définir le groupe sous lequel PHP-FPM s'exécutera
group = www-data

; Spécifier le port ou socket sur lequel PHP-FPM écoutera
listen = 9000

; Définir le propriétaire du socket d'écoute
listen.owner = www-data

; Définir le groupe du socket d'écoute
listen.group = www-data

; Ajuste le nombre de processus enfants actifs selon la charge de travail
pm = dynamic

; Nombre maximum de processus enfants
pm.max_children = 5

; Nombre de processus enfants à lancer au démarrage
pm.start_servers = 2

; Nombre minimum de processus enfants en attente
pm.min_spare_servers = 1

; Nombre maximum de processus enfants en attente
pm.max_spare_servers = 3

; Nombre maximum de requêtes qu'un processus enfant peut traiter avant de se fermer
pm.max_requests = 100

; Ne pas effacer les variables d'environnement
clear_env = no